[package]
name = "blockchain-rs"
version = "0.1.0"
authors = ["Joseph Lai <jlai24142@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
data-encoding = "2.3.2"
ring = "0.16.20"
