[package]
name = "asb"
version = "0.1.0"
authors = ["Joseph Lai <jlai24142@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
data-encoding = "2.3.2"
ring = "0.16.20"
structopt = "0.3.22"

[dev-dependencies]
assert_cmd = "1.0.7"
